### PR TITLE
WIP: Progressive Web App Support For Issue #98

### PR DESCRIPTION
**Pull request by jaetoole**
This is a WIP for PWA support for issue #98

### CODE REVIEW

**Comment by ash-jc-allen** [comment]
Hey @jaetoole! Nice one for doing this much on this feature already.

I'll get hold of the images at some point this week for you and get them sent over 😄

**Comment by jaetoole** [comment]
@ash-jc-allen what else would you think needs adding? I've got the titles there now, I've also done the logos and resized that (if they are the ones you would like me to use). I've also set the colours to what I think are brand colours.

I'm not opposed to writing a quick test just to ensure the service worker file and manifest.json is present if you would like?

Other than the splash image, let me know if there's anything else I can tweak - PWAs are not my forte but something I really wanted to learn so it's been a good opportunity.

**Comment by ash-jc-allen** [comment]
I've just pushed up some icons and splash screens for us to use. I'll hopefully be able to take a look at this later today and we can get it released.

I'm not too clued up on PWAs either, but I think we should have everything covered 🙂

**Comment by ash-jc-allen** [comment]
Huge thanks for this @jaetoole! Apologies that it's taken a while to get it merged. I'm going to get this merged in now and give it a spin on the live site 😄

**Pull request merged**
