### PR TITLE
README File Improvement

### PR DESCRIPTION
**Pull request by GurpreetkaitCode**
I am a beginner and haven't used sail before. Then I saw that there were two commands that were missing from a beginner's point of view. That's why I have added two points there So that, a beginner can understand the complete roadmap.

### CODE REVIEW

**Comment by ash-jc-allen** [comment]
Hey @GurpreetkaitCode, thanks for the PR!

I'm not quite sure that this is needed? `laravel/sail` is a dependency in the `composer.json` file so it should already be installed and ready to use after you've run `composer install` when first installing the dependencies?

**Comment by GurpreetkaitCode** [comment]
It wasn't working, when I did that. May be some problem on my end. Thanks

**Comment by ash-jc-allen** [comment]
Were you getting any errors at all? 🙂

**Comment by GurpreetkaitCode** [comment]
No, I might have missed something there 🙂

**Comment by ash-jc-allen** [comment]
No problem. In that case, I'll close this PR. But give me a shout if you run into any more issues 🙂

**Pull request closed without merging**
