### PR TITLE
Add an option to show the sidebar on mobile devices

### PR DESCRIPTION
**Pull request by rubenvanerk**
With #77 merged we can now ignore issues without getting a warning. On mobile there is currently no way of viewing the ignored issues. This PR adds an option to show the sidebar so ignored issues can be shown and un-ignored.

image

### CODE REVIEW

**Comment by ash-jc-allen** [comment]
Hey @rubenvanerk! It looks like there's a merge conflict on this PR. If you get a few spare minutes, would you be able to check it out for me, please? If not, I'll take a look at it 🙂

**Comment by rubenvanerk** [comment]
Yes, I'll have a look!

**Comment by rubenvanerk** [comment]
Merged!

And swapped the text for a button:
image

**Comment by ash-jc-allen** [comment]
Huge thanks for this Ruben! 😄

I've just made a few small tweaks because the 'show filter' button seemed to be showing on desktop mode, but it was only a quick fix. I'll get this merged now!

**Pull request merged**
