### PR TITLE
Added keyboard shortcut for search

### PR DESCRIPTION
**Pull request by jeroen-hso**
Fixes https://github.com/ash-jc-allen/find-a-pr/issues/120

- requires alpinejs/focus plugin
- added keyup window event in list issues blade

### CODE REVIEW

**Comment by ash-jc-allen** [comment]
Hey @jeroen-hso, thanks for the PR! This is really cool! 😄

I've just given it a quick test and it seems to work on Chrome. But when I tested it on Firefox, pressing the `/` key triggers Firefox's "Quick Find" feature so it doesn't highlight the search box.

Are you aware of any fixes for this? If not, I can do some investigating later 🙂

**Comment by rubenvanerk** [comment]
`ctrl` + `k` seems to be a popular choice for activiting search:
- [Tailwind CSS](https://tailwindcss.com/)
- [Alpine.js](https://alpinejs.dev/)

Maybe because the `/` conflict in Firefox?

**Comment by ash-jc-allen** [comment]
I did consider using that as well as (or instead of) the `/`. Maybe we can add that in too?

In the Laravel docs, it looks like you can use `/` without the conflict in Firefox? So I'm guessing it should be possible to use `/`. I'm wondering if there's something that we're missing in the event handler for the key press? 🤔

**Comment by jeroen-hso** [comment]
This works:
`@keydown.slash.window.prevent="$refs.search.focus()"`

But the problem is that you can't type `/` in the search field anymore. This workaround works, but coding is not so pretty. Maybe you can do it cleaner.

**Comment by rubenvanerk** [comment]
> This works:
> @keydown.slash.window.prevent="$refs.search.focus()"

I think this is a good solution! Laravel.com also doesn't allow you to type a `/` in the search box.

**Comment by ash-jc-allen** [comment]
Yeah that's a really good point that I hadn't noticed! I'm happy with that solution if it works 😄

**Comment by jeroen-hso** [comment]
> > This works:
> > @keydown.slash.window.prevent="$refs.search.focus()"
> 
> I think this is a good solution! Laravel.com also doesn't allow you to type a `/` in the search box.
PR is updated and I have added search key hint (similar to Laravel search)

image

@ash-jc-allen I hope you like it.

**Review by rubenvanerk — APPROVED** [review]

**Comment by ash-jc-allen** [comment]
Perfect, thank you @jeroen-hso!

And thanks @rubenvanerk for helping out too 🔥

**Pull request merged**
