### PR TITLE
Don't chunk repos for fetching issues

### PR DESCRIPTION
**Pull request by rubenvanerk**
After [your comment ](https://github.com/ash-jc-allen/find-a-pr/pull/123#issuecomment-1214885933), I did some testing and didn't notice a big performance decrease.
With chunking, there could also be the problem of a failing job that then doesn't fetch new issues for the other repos that were in the collection.

### CODE REVIEW

**Comment by ash-jc-allen** [comment]
Thanks for these changes! I know that the stats won't be 100% accurate because you're running it locally, but what sorts of times were you getting with and without the batching?

For reference, I've got 5 queue workers running on the production site, and it takes about 36 seconds to load all of the repos.

And that's a great point about loading the other repos that I hadn't considered either! 🙂

**Comment by rubenvanerk** [comment]
Just quikcly tested the following:

- I removed the Spatie repo's (so the test is a _bit_ faster :wink: )
- Started 3 workers with `artisan work`
- Ran `repos:preload`

With master it took 50s, with these changes it actually took 45s. 

I think it's because of this: there's always a last job that needs to be executed. With chunking, one job/worker has to load all those last repo's by itself, the other 4 workers are then on standby and can't help. Without chunking, all workers can help with the last repo's.

**Comment by rubenvanerk** [comment]
> Just quickly tested the following:
> 
> - I removed the Spatie repo's (so the test is a _bit_ faster :wink: )
> - Started 3 workers with `artisan queue:work`
> - Ran `repos:preload`
> 
> With master, it took 50s, with these changes it actually took 45s. 
> 
> I think it's because of this: there's always a last job that needs to be executed. With chunking, one job/worker has to load all those last repo's by itself, the other 4 workers are then on standby and can't help. Without chunking, all workers can help with the last repo's.

**Comment by ash-jc-allen** [comment]
Sweet! I've merged this in so it's running on production now. I'll do some quick testing tonight to see how much faster it is for us 😄

**Comment by ash-jc-allen** [comment]
Hey @rubenvanerk! I've just done some testing with this on the production site.

It seems that with these changes, it's taking 3min 42s to run through all the jobs. I'm just wondering if you've got any ideas on this? That seems like a pretty long time haha! 😄

**Comment by ash-jc-allen** [comment]
Just for a quick update, I reverted the PR back so it's using the batching and the preloading took 41 secs to run

**Pull request merged**
