### PR TITLE
Making the labels in the sidebar usable as search filters

### PR DESCRIPTION
**Pull request by philipsorensen**
I was really surprised the labels in the sidebar did nothing, so I made them usable as search filters that can be toggled. If an issue has any of the enabled labels it is shown. There's a couple of different ways, you could do this, but I think this is the most straightforward. 

Also a slight update of the readme.

### CODE REVIEW

**Comment by ash-jc-allen** [comment]
Hey @philipsorensen! You're absolutely right about expecting the labels to work as buttons. It's something that I've wanted to add since I first built Find A PR, but I kept forgetting haha! So I'm definitely all for this addition 😄

I'll check out this PR now and see if we can get it merged today 😎

**Comment by ash-jc-allen** [comment]
Just from having a quick browse through this, it looks great! I do have an idea for a possible improvement though if you're interested in an extra contribution?

I think it'd be really cool to display the number of issues that each label on the label itself. For example, the list of labels on the left hand side could be:

- findapr (3)
- first good issue (0)
- first issue (10)
- first pr (100)
- help wanted (20)

What's your opinion on adding something like that? And it's totally cool if you'd prefer not to add it by the way 😄

**Comment by philipsorensen** [comment]
Great idea with the numbers. I'm looking into it. 😎

**Comment by ash-jc-allen** [comment]
Huge thank you again for this PR, @philipsorensen! I'm really sorry it took so long to get merged in (life has been so busy!). Your changes should be deploying to production now 😄

**Pull request merged**
